### ISSUE TITLE
Would it possible to have the option to add another bar to the bottom of the page?

### ISSUE THREAD

**Issue by Amer-xyz** [Meldo-Megimi/EH-Page-Scrobbler#10]
Most of the time when I want to switch pages is after I scrolled to the bottom of the current one, and I don't think it's very user friendly to have to scroll all the way up to use the page scroller again.

**Comment by Meldo-Megimi** [comment]
Implemented with commit https://github.com/Meldo-Megimi/EH-Page-Scrobbler/commit/61797471c6bf550d041d83b3d0c8adb5dc979875 => version 2022.11.12.01
