### ISSUE TITLE
[Firefox 107 - Tampermonkey 4.18.1] - New Settings dialog appears under gallery links in Minimal/Minimal+ 

### ISSUE THREAD

**Issue by Shigbeard** [Meldo-Megimi/EH-Page-Scrobbler#11]
As it says on the can. Links to galleries appear over the top of the menu when using Minimal or Minimal+. This issue doesn't occur with Compact, Extended, or Thumbnail views

**Comment by Meldo-Megimi** [comment]
is fixed in https://github.com/Meldo-Megimi/EH-Page-Scrobbler/commit/28c23de0b9f47fc1e84ad1367dba57d602f671db => 2022.11.19.01
