### ISSUE TITLE
好像没有效果？

### ISSUE THREAD

**Issue by lhj5426** [Meldo-Megimi/EH-Page-Scrobbler#2]
![image](https://user-images.githubusercontent.com/30548000/200054599-d51943ec-2a3a-4500-9f3d-378b29e89152.png)
好像没有效果呢 是bug吗 一整条都是绿的 全是0 点击 一直是当前页面

**Comment by Qserty-EH** [comment]
Make sure to visit the frontpage once in a while, url should be exhentai.org with nothing behind.
When you visit the frontpage the script parse the page to get the current max GID and store it into the localstorage (key "EHPS-maxGID")
In your screenshot we can see it's still "null", so it's likely you skipped the front page or something is preventing the script from working.

**Comment by Meldo-Megimi** [comment]
As it shows null in the lower left, it is not the newest version ;)
I recommend to update the script to the newest version as this problem should now better handled.

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/200113548-4f8c071b-53ec-45b9-8183-72d45c00dc0e.png)
It works fine after the update

**Comment by Meldo-Megimi** [comment]
I'm glad that it  works now :)
