### ISSUE TITLE
Script will not install on Firefox (106.0.4) with Greasemonkey (4.11)

### ISSUE THREAD

**Issue by TopCat00** [Meldo-Megimi/EH-Page-Scrobbler#4]
Generates the following error:

User script download failed

    Ignoring @match pattern http*://e-hentai.org/* because: Error: @match: Invalid protocol (http*:) specified.

**Comment by Meldo-Megimi** [comment]
Should now be fixed with update https://github.com/Meldo-Megimi/EH-Page-Scrobbler/commit/561d657fe4c07163154dc1aef8161ad932aef58d

**Comment by TopCat00** [comment]
Yes, it can install now. Thanks.
