### ISSUE TITLE
Non-search Items in local storage being displayed in Saved Searches

### ISSUE THREAD

**Issue by TopCat00** [Meldo-Megimi/EH-Page-Scrobbler#6]
I have other scripts used for site that also use local storage.  Scrobbler is attempting to use these items as Saved Searches.
Firefox 106.0.5 Greasemonkey 4.11

![image](https://user-images.githubusercontent.com/48459110/200190657-707949a5-3611-4779-9fbc-64218e03d127.png)

**Comment by Meldo-Megimi** [comment]
Should now be fixed with Version 2022.11.07.01 => https://github.com/Meldo-Megimi/EH-Page-Scrobbler/commit/331898a09ea26ed811643a417c15b184ad1f5957
