### ISSUE TITLE
Using browser back button causes Search to duplicate

### ISSUE THREAD

**Issue by TopCat00** [Meldo-Megimi/EH-Page-Scrobbler#7]
Visiting a gallery or using Next and then using browser back navigation causes Search to duplicate.  Repeatedly using browser navigation causes more and more duplicates to appear.
Firefox 106.0.5 Greasemonkey 4.11

![image](https://user-images.githubusercontent.com/48459110/200211824-e7721d17-b09c-4be5-8151-e3cbf4c99beb.png)

**Comment by Meldo-Megimi** [comment]
I can't reproduce it here with my system (Firefox 106.0.5 and Tampermonkey 4.18.0) but I look at it

**Comment by Meldo-Megimi** [comment]
I have changed the script to check if the elemens are already there. Version 2022.11.07.02 =>  https://github.com/Meldo-Megimi/EH-Page-Scrobbler/commit/244b18e699aaae315b647390d61d51bbd42ccb20
Can you please check it again?

**Comment by TopCat00** [comment]
Fixed.  No duplication now.

**Comment by Meldo-Megimi** [comment]
Thanks for testing :)
