### ISSUE TITLE
Error thrown when attempting to save Search

### ISSUE THREAD

**Issue by TopCat00** [Meldo-Megimi/EH-Page-Scrobbler#8]
Thanks for all your hard work on this.

Script throws error when attempting to save Search
Firefox 106.0.5 Greasemonkey 4.11

![image](https://user-images.githubusercontent.com/48459110/200212814-9d5650c4-2a90-48cc-93b2-60da34001a1e.png)

**Comment by Meldo-Megimi** [comment]
This again I can't reproduce with Tempermonkey :( 
I try to install Greasemonkey to find the problem.

**Comment by Meldo-Megimi** [comment]
This is (in my opinion) a bug in Greasemonkey. Greasemonkey  blocks the unsafeWindow call.
I have implemented a workaround but i strongly suggest to dump Greasemonkey and switch to Tempermonkey ;)
In Version 2022.11.07.04 => https://github.com/Meldo-Megimi/EH-Page-Scrobbler/commit/6f8c40e514b9c9954ab839b4ba2f949cd94c80e4 it should work with Greasemonkey.

**Comment by TopCat00** [comment]
Yes, save and load works now.  Thanks.
