### ISSUE TITLE
relative dynamic pagination not really working at all

### ISSUE THREAD

**Issue by 117649** [Meldo-Megimi/EH-Page-Scrobbler#9]
I have multiple tabs for search result opened. The page number just composed of links that not of the search queue of the tab it on.

It's better you just use per-load to build pagination for current tab.

**Comment by Meldo-Megimi** [comment]
Yes, the problems with multiple tabs are a limitation that I'm aware about.
I'm working on this topic.

**Comment by Meldo-Megimi** [comment]
Pagination is now compatible with tabs but I have to disable it for any other script engine but Tampermonkey

**Comment by Meldo-Megimi** [comment]
Changed the method again and now all script engines should be working

**Comment by 117649** [comment]
I have this piece of code that goes on forever to get next page of next page. 
May be use something like this to populate about 10 page numbers when open a new search result.

```js
async function f(u,i = 0){
  i++;
  var t = await fetch(u);
  var t1 = (await t.text()).match(new RegExp("http[^<]*next=(\\d*)"));
  var t2 = t1[0];
  console.log(i+","+t1[1]);
  if(t2) f(t2,i);
};
```

**Comment by Meldo-Megimi** [comment]
I will look into this, but I'm a little concerned about the load that this generates at the server side.

**Comment by 117649** [comment]
> I will look into this, but I'm a little concerned about the load that this generates at the server side.

You'll be capped for too many request too little time.
But last time I run that it goes 525 pages before got blocked.

**Comment by Meldo-Megimi** [comment]
I think I implement a prefetch for pagination as a optional, default disabled, function. Then the user can itself decide if it's worth ;)

**Comment by Meldo-Megimi** [comment]
It's implemented with commit https://github.com/Meldo-Megimi/EH-Page-Scrobbler/commit/7cdd4e310a3145a37d2109a109e095fb36aa9d2f 
You have to enable it in the options (red star in the middle of the bar).

**Comment by 117649** [comment]
![image](https://user-images.githubusercontent.com/8281345/201157909-fe8d0ab2-6610-4527-a6d1-4de645354111.png)
On the first page but page number is not.
Logic are needed here to check if currently on the first page of the result or first page is within pre-fetch range and to recreate the pagination. Because new added galleries would offset the GID lead to next page.

I would suggest if currently is on first page re-fetch and recreate pagination. If first page is only in pre-fetch range check if a whole new page is inserted between page 0 and 1, only recreate pagination after that happened.

**Comment by Meldo-Megimi** [comment]
^^ I have not thinked that the user will tamper with the parameters in the url :/
I will rethink the pagionation reset funktion ;)

**Comment by 117649** [comment]
> ^^ I have not thinked that the user will tamper with the parameters in the url :/ I will rethink the pagionation reset funktion ;)

It not need to tamper with parameters. If you stay at first page as time goes by new galleries will be add and GID to next page will be offset by them.

Also what in url should be the same of your search query with options.

**Comment by Meldo-Megimi** [comment]
I think there are two different problems:
a) the one that the page indicator is not updated (the only way this can happen is  that the user edited the URL)
b) how to deal with new galleries

For a) the solution is to detect that the user have played with the URL and reset the paginator. 
But for b) I think the solution is already implemented, as the paginator will add negative pages if new galleries are added. That's he have to do anyways if you jump to any GID. It's a why I called it a relative dynamic paginator.

**Comment by Meldo-Megimi** [comment]
a) should now be fixed with commit https://github.com/Meldo-Megimi/EH-Page-Scrobbler/commit/c2bfa9ab1ecf208e3312c57f1e450a235354c1c6

**Comment by 117649** [comment]
![image](https://user-images.githubusercontent.com/8281345/201428218-72af04d4-c352-4d94-9d38-88259065cb09.png)

Still page number is not aligned on first page.
Try check if user is on the first page and if next page button are lead to same place as page number 1. Then reset pagination if two are not matched.

Have you considered that browser have back and forward buttons? The url could be way different between two history record in a session.
And search query is reflected in the url.
I never touched url bar at all for any circumstance I mentioned in this thread. There just no need.

**Comment by Meldo-Megimi** [comment]
The browser buttons have previously worked... and should now work again ;)

**Comment by 117649** [comment]
Just found when I'm on url like this:
https://exhentai.org/tag/artist:mankai+kaika
It will redirect me to something like:
https://exhentai.org/tag/artist:mankai+kaika?next=2374470
Where 2374470 is the GID of the first gallery of the result. 

And it s caused by:https://github.com/Meldo-Megimi/EH-Page-Scrobbler/blob/348f3bd93c6df0188bd3ff7cfa0b84dd608455ee/PageScrobbler.user.js#L282

This just should not be happen at all.
Took user to another url without user action and approve is really bizarre.

**Comment by Meldo-Megimi** [comment]
The modify of the URL on the first page of a search is necessary for reliable pagination the alternative is to restart the pagination from scratch if the user reloads the page which is worse in my opinion.

**Comment by 117649** [comment]
> The modify of the URL on the first page of a search is necessary for reliable pagination the alternative is to restart the pagination from scratch if the user reloads the page which is worse in my opinion.

If user is on first page restart from scratch is completely OK and should be the default behavior.
Save and check the link to next page on the first page when reload to decide if a completely restart is needed.

Maybe point page number 0 to the GID of the first page or make an option to let user opt-in.
Force redirect is just malware level bizarre.

**Comment by Meldo-Megimi** [comment]
I don't see the point, now all is working fine and the only hassle is that on the first page of a search the browser URL is extended with the current GID, the page is not even redirected or reloaded.

This is a point where I for myself say, it's not worth to spend more time in it. If anyone else want to do it, I will happily accept it and approve any Pull Requests.

**Comment by 117649** [comment]
I've comment out that line seems enough for now.
